name: Run check

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-check:
    runs-on: macos-latest
    env:
      DEBUG: pw:api

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - shell: bash
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo  "Secret is: $TELEGRAM_BOT_TOKEN"

      - name: Installing dependencies for all browsers...
        run: npx playwright install-deps

      - name: Installing dependencies...
        run: yarn

      - name: Running script...
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: yarn run-check-stock
